---
- name: Get public IP address
  command: gcloud compute addresses describe k8s-the-easy-way --region us-central1 --format 'value(address)'
  register: k8s_public_address

- name: Create Kubernetes CSR
  template:
    src: roles/workstation/templates/kubernetes-csr.json
    dest: roles/workstation/files/kubernetes-csr.json

- name: Create CA certs
  shell: cfssl gencert -initca roles/workstation/files/ca-csr.json | cfssljson -bare roles/workstation/files/certs/ca

- name: create admin certs
  shell: cfssl gencert -ca=roles/workstation/files/certs/ca.pem -ca-key=roles/workstation/files/certs/ca-key.pem -config=roles/workstation/files/ca-config.json -profile=kubernetes roles/workstation/files/admin-csr.json | cfssljson -bare roles/workstation/files/certs/admin

- name: create kube-proxy certs
  shell: cfssl gencert -ca=roles/workstation/files/certs/ca.pem -ca-key=roles/workstation/files/certs/ca-key.pem -config=roles/workstation/files/ca-config.json -profile=kubernetes roles/workstation/files/kube-proxy-csr.json | cfssljson -bare roles/workstation/files/certs/kube-proxy

- name: create kubernetes certs
  shell: cfssl gencert -ca=roles/workstation/files/certs/ca.pem -ca-key=roles/workstation/files/certs/ca-key.pem -config=roles/workstation/files/ca-config.json -profile=kubernetes roles/workstation/files/kubernetes-csr.json | cfssljson -bare roles/workstation/files/certs/kubernetes
