---
- name: Distribute Worker certs
  copy:
    src: "{{ item }}"
    dest: /var/tmp
    owner: root
    group: root
    mode: 0644
  with_items:
    - roles/workstation/files/certs/ca.pem
    - roles/workstation/files/certs/kube-proxy.pem
    - roles/workstation/files/certs/kube-proxy-key.pem
  become: true
