---
- name: Distribute kubeconfig files
  copy:
    src: "{{ item }}"
    dest: /var/tmp
    owner: root
    group: root
    mode: 0644
  with_items:
    - roles/workstation/files/kubeconfig/bootstrap.kubeconfig
    - roles/workstation/files/kubeconfig/kube-proxy.kubeconfig
  become: true
